### ISSUE TITLE
Failed to activate the AtomicChar package

### ISSUE THREAD

**Issue by yimingli** [SaschaNaz/AtomicChar#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Mac OS X 10.11
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.8
### Stack Trace

Failed to activate the AtomicChar package

```
At this.getVerticalScrollbarWidth is not a function

TypeError: this.getVerticalScrollbarWidth is not a function
  at DisplayBuffer.atmcGetEditorWidth (/Users/paul/.atom/packages/atomicchar/lib/atomic-wrapper.js:67:33)
  at DisplayBuffer.atmcGetSoftWrapWidth (/Users/paul/.atom/packages/atomicchar/lib/atomic-wrapper.js:71:38)
  at DisplayBuffer.getSoftWrapColumn (/Users/paul/.atom/packages/atomicchar/lib/atomic-wrapper.js:63:25)
  at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:1202:73)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:1153:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateAllScreenLines (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:238:19)
  at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:308:12)
  at /Users/paul/.atom/packages/atomicchar/lib/atomic-wrapper.js:111:30
  at Workspace.module.exports.Workspace.observeTextEditors (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at Object.exports.activate (/Users/paul/.atom/packages/atomicchar/lib/atomic-wrapper.js:110:20)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom-beta/1.1.0-beta1/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -9:14 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -9:03.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:14.6.0 core:copy (div.release-notes.padded.pane-item.native-key-bindings)
     -0:12.5.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
     -0:10.8.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "fancy-new-file",
      "autocomplete",
      "markdown-helpers",
      "language-objective-c",
      "image-view",
      "language-coffee-script",
      "language-javascript",
      "language-property-list",
      "language-ruby-on-rails",
      "open-on-github",
      "terminal-panel",
      "git-log",
      "tabs-to-spaces",
      "deprecation-cop",
      "exception-reporting",
      "set-syntax",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-sass",
      "language-sql",
      "language-todo",
      "language-toml",
      "language-xml",
      "welcome",
      "metrics",
      "package-generator",
      "aligner",
      "atom-alignment",
      "gistom",
      "markdown-format",
      "linter",
      "convert-to-utf8"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
AtomicChar, v0.3.8
Sublime-Style-Column-Selection, v1.3.0
autocomplete-paths, v1.0.2
file-icons, v1.6.11
highlight-selected, v0.10.1
language-latex, v0.6.1
language-r, v0.4.0
language-stata, v0.1.0
markdown-preview-plus, v2.2.2
minimap, v4.15.0
minimap-git-diff, v4.1.8
project-manager, v2.6.5
vim-mode, v0.62.0

# Dev
No dev packages
```

**Comment by saschanaz** [comment]
Just fixed by 404df2d1cbacc2b0694ba3eddd58fb9105b00e2f, thanks!
