### ISSUE TITLE
Uncaught TypeError: this.getScrollWidth is not a function

### ISSUE THREAD

**Issue by ellisfan** [SaschaNaz/AtomicChar#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.8
### Stack Trace

Uncaught TypeError: this.getScrollWidth is not a function

```
At C:\Users\Administrator\.atom\packages\AtomicChar\lib\atomic-wrapper.js:66

TypeError: this.getScrollWidth is not a function
    at DisplayBuffer.atmcGetEditorWidth (C:\Users\Administrator\.atom\packages\AtomicChar\lib\atomic-wrapper.js:66:64)
    at DisplayBuffer.atmcGetSoftWrapWidth (C:\Users\Administrator\.atom\packages\AtomicChar\lib\atomic-wrapper.js:74:29)
    at DisplayBuffer.getSoftWrapColumn (C:\Users\Administrator\.atom\packages\AtomicChar\lib\atomic-wrapper.js:63:25)
    at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\src\display-buffer.js:1202:73)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\src\display-buffer.js:1153:20)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\src\display-buffer.js:1130:19)
    at C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\src\display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TokenizedBuffer.module.exports.TokenizedBuffer.retokenizeLines (C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tokenized-buffer.js:222:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.grammarAddedOrUpdated (C:\Users\Administrator\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tokenized-buffer.js:110:23)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "csslint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
AtomicChar, v0.3.8
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.13
file-icons, v1.6.11
jshint, v1.8.1
laravel, v0.7.0
minimap, v4.15.0
pretty-json, v0.4.1
wakatime, vundefined

# Dev
No dev packages
```

**Comment by saschanaz** [comment]
v0.3.9 will fix this. Thanks!
