### ISSUE TITLE
Failed to load the AtomicChar package

### ISSUE THREAD

**Issue by ellisfan** [SaschaNaz/AtomicChar#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Deepin 2014.3
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.9
### Stack Trace

Failed to load the AtomicChar package

```
At Cannot find module 'src/tokenized-line'

Error: Cannot find module 'src/tokenized-line'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AtomicWrapper (/home/bantes/.atom/packages/AtomicChar/lib/atomic-wrapper.js:5:25)
    at Object.<anonymous> (/home/bantes/.atom/packages/AtomicChar/lib/atomic-wrapper.js:101:3)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
AtomicChar, v0.3.9
minimap, v4.16.0

# Dev
No dev packages
```

**Comment by saschanaz** [comment]
This should now be fixed by v0.3.10. Thank you very much! :+1:

**Comment by CreatorMetaSky** [comment]
when I update to the version v0.3.10, It also error:

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.10

### Stack Trace

Failed to load the AtomicChar package

```
At Cannot find module '//resources/app.asar/src/tokenized-line'

Error: Cannot find module '//resources/app.asar/src/tokenized-line'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at AtomicWrapper (/Users/CoderAFI/.atom/packages/AtomicChar/lib/atomic-wrapper.js:7:25)
    at Object.<anonymous> (/Users/CoderAFI/.atom/packages/AtomicChar/lib/atomic-wrapper.js:107:3)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "batman-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
AtomicChar, v0.3.10
batman-syntax, v1.0.1
linter, v1.11.1
nucleus-dark-ui, v0.6.9
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by saschanaz** [comment]
~~@CoderAFI Can you open dev tool (View->Developers->Toggle Developer Tools), type this, and tell me what the result is? It seems I have to be sure how directories are structured in OS X.~~

~~`var module = require("module"); module.globalPaths`~~

**Comment by saschanaz** [comment]
@CoderAFI Never mind, please try v0.3.11 and check it works now. Thanks! (Courtesy of https://github.com/raccy/atom-wrap-style/commit/0e86fb530f1b16f763168af6a89d4bb9834da9e0)
