### ISSUE TITLE
Failed to activate the AtomicChar package

### ISSUE THREAD

**Issue by ex-jedi** [SaschaNaz/AtomicChar#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.11
### Stack Trace

Failed to activate the AtomicChar package

```
At Cannot find module 'C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar/src/display-buffer'

Error: Cannot find module 'C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar/src/display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at AtomicWrapper (C:\Users\Mark\.atom\packages\AtomicChar\lib\atomic-wrapper.js:7:25)
    at Object.<anonymous> (C:\Users\Mark\.atom\packages\AtomicChar\lib\atomic-wrapper.js:106:3)
    at Module._compile (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:173:16)
    at C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:92:15)
    at C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\atom-environment.js:760:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "deprecation-cop",
      "wrap-guide",
      "linter-sass-lint"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-bracket-highlight, v0.3.1 (inactive)
atom-color-highlight, v3.0.9 (inactive)
AtomicChar, v0.3.11 (inactive)
block-cursor, v0.13.1 (inactive)
color-picker, v2.2.2 (inactive)
css-snippets, v0.9.0 (inactive)
emmet, v2.4.3 (inactive)
emmet-snippets-compatibility, v1.0.6 (inactive)
highlight-selected, v0.11.2 (inactive)
jshint, v1.8.5 (inactive)
linter, v1.11.14 (inactive)
linter-htmlhint, v1.3.0 (inactive)
linter-scss-lint, v3.0.4 (inactive)
minimap, v4.24.7 (inactive)
minimap-autohide, v0.10.1 (inactive)
minimap-bookmarks, v0.3.1 (inactive)
minimap-codeglance, v0.4.5 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-git-diff, v4.3.1 (inactive)
minimap-selection, v4.4.0 (inactive)
monokai, v0.18.0 (inactive)
monokai-seti, v0.7.0 (inactive)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (inactive)
pigments, v0.31.2 (inactive)
project-manager, v2.9.7 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
swackets, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.2 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.0 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by coderbiq** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.7
**System**: Mac OS X 10.10.5
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.11

### Stack Trace

Failed to activate the AtomicChar package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at AtomicWrapper (/Users/macbookair/.atom/packages/AtomicChar/lib/atomic-wrapper.js:7:25)
    at Object.<anonymous> (/Users/macbookair/.atom/packages/AtomicChar/lib/atomic-wrapper.js:106:3)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:760:28
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "php-cs-fixer",
      "atom-autocomplete-php",
      "phpunit",
      "activate-power-mode",
      "terminal-plus",
      "glist",
      "go-imports",
      "file-icons",
      "git-history",
      "gorename",
      "markdown-pdf",
      "move-panes",
      "atom-typescript"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1 (inactive)
atom-autocomplete-php, v0.18.9 (inactive)
atom-beautify, v0.29.10 (inactive)
AtomicChar, v0.3.11 (inactive)
autocomplete-go, v1.1.0 (inactive)
builder-go, v1.0.0 (inactive)
color-picker, v2.2.2 (inactive)
docblockr, v0.7.3 (inactive)
docs-snippets, v0.8.0 (inactive)
environment, v1.2.0 (inactive)
ex-mode, v0.10.0 (inactive)
file-icons, v1.7.17 (inactive)
git-control, v0.8.2 (inactive)
git-history, v3.2.0 (inactive)
go-config, v1.2.1 (inactive)
go-get, v1.0.3 (inactive)
go-plus, v4.1.0 (inactive)
gofmt, v1.1.6 (inactive)
gometalinter-linter, v1.1.0 (inactive)
gorename, v1.0.2 (inactive)
japanese-wrap, v0.2.7 (inactive)
language-typescript-grammars-only, v1.5.0 (inactive)
linter, v1.11.14 (inactive)
markdown-pdf, v1.5.0 (inactive)
move-panes, v0.2.0 (inactive)
navigator-godef, v1.0.3 (inactive)
pane-layout-plus, v0.7.3 (inactive)
platformio-ide-terminal, v2.1.1 (inactive)
project-manager, v2.9.7 (inactive)
sync-settings, v0.7.2 (inactive)
tester-go, v1.0.4 (inactive)
vim-mode, v0.65.1 (inactive)
vim-mode-visual-block, v0.2.15 (inactive)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by saschanaz** [comment]
Hi people, I'm sorry to say that AtomicChar is currently not in active development as Atom team has their own solution (https://github.com/atom/atom/issues/9447) and I'm currently using VSCode instead of Atom.

**Comment by ex-jedi** [comment]
Thanks for all your hard work @SaschaNaz. Much appreciated.
